### ISSUE TITLE
Question about underscore

### ISSUE THREAD

**Issue by jcubic** [internet-development/www-server-mono#10]
I used the font with my library [jQuery Terminal](https://terminal.jcubic.pl/), and the ASCII Art looks odd because the underscore is way too height.

Default Linux monospace font
![Przechwycenie obrazu ekranu_2024-08-27_13-45-56](https://github.com/user-attachments/assets/e8e63b10-49e7-486c-94cc-c4bf56798823)

server mono
![Przechwycenie obrazu ekranu_2024-08-27_13-45-25](https://github.com/user-attachments/assets/01d12927-1c1c-4fd6-84c7-052a86586d4d)

Is there something that can be done to make the underscore a little bit lower, so the ASCII Art looks similar to monospace. Or is this by design?

https://codepen.io/jcubic/pen/poXKQrO

**Comment by jimmylee** [comment]
Thanks for reporting this @jcubic !
