### ISSUE TITLE
The digit "1" and the letter "l" are too close in shape

### ISSUE THREAD

**Issue by drewhk** [internet-development/www-server-mono#3]
Is it possible to ask for a variant with a bit more distinguishable shapes for these two symbols? I have literally fallen in love first sight with your font, my only issue is legibility of mixed digit-letter identifiers. Your font would be ideal for data intensive applications, but this is a shortcoming. I would edit the font myself to make my own variant, but I have no idea about font design and how to even approach this... Is it maybe possible to disambiguate these symbols a bit more?

**Comment by jimmylee** [comment]
It is totally possible @drewhk, we'll look at this for our second release candidate.

**Comment by jimmylee** [comment]
Thank you for bringing this up! This is now resolved, enjoy.

**Comment by drewhk** [comment]
Wonderful, and thank you for the very quick response! I will keep an eye on the next release.
