### ISSUE TITLE
Export Glyphs document to Unified Font Object (UFO)

### ISSUE THREAD

**Issue by oznogon** [internet-development/www-server-mono#4]
While Glyphs is a lovely tool, it's a closed-source Mac-only app whose format is poorly supported by other tools, such as FontForge.

Glyphs supports [exporting](https://handbook.glyphsapp.com/export/#export/ufo) to the Unified Font Object (UFO) 3 format, which is much more portable and [SIL's recommended format for open projects](https://silnrsi.github.io/FDBP/en-US/UFO.html) that intend to follow font development best practices.

It would be beneficial for this openly licensed font's source to also be accessible in the more open UFO format under the same license as the Glyphs source.

**Comment by jimmylee** [comment]
Thank you for mentioning this! I have made a note to add an export to the United Font Object (UFO) 3 format.

**Comment by jimmylee** [comment]
Addressed in https://github.com/internet-development/www-server-mono/pull/13

**Comment by oznogon** [comment]
Thank you!
