### ISSUE TITLE
Incorrect rendering for some glyph

### ISSUE THREAD

**Issue by SeolHa314** [internet-development/www-server-mono#7]
![image](https://github.com/user-attachments/assets/dc00885e-0df8-4940-b490-9d7ab3a92749)
Hello,

When two lines overlaps, sometimes it makes a small hole in the glyph.
These lines should be merged, right?
However, on version 0.0.1 it seems okay.

![image](https://github.com/user-attachments/assets/7198a463-2f72-4fc7-b2e3-27b6bbbeb435)
0.0.1 / 0.0.2

**Comment by jimmylee** [comment]
Thank you for reporting this!

**Comment by jimmylee** [comment]
<img width="1111" alt="Screenshot 2024-08-13 at 10 35 48 AM" src="https://github.com/user-attachments/assets/4c89156c-c372-4a94-8035-3a6435f66711">

Really sorry about that @SeolHa314, this is resolved in the latest release.

**Comment by SeolHa314** [comment]
@jimmylee Thanks!
